# Generated by Django 2.0.4 on 2022-06-08 17:37

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180403_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num_plants',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='plant_type',
            field=models.CharField(default=datetime.datetime(2022, 6, 8, 17, 37, 36, 168496, tzinfo=utc), max_length=80),
            preserve_default=False,
        ),
    ]
