# Generated by Django 2.2 on 2022-07-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220608_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='project',
            name='lat',
            field=models.FloatField(default=80),
        ),
        migrations.AddField(
            model_name='project',
            name='lon',
            field=models.FloatField(default=80),
        ),
    ]
