# Generated by Django 2.2 on 2022-07-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220704_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
