# Generated by Django 4.1.2 on 2022-11-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_alter_userprofile_friends'),
        ('projects', '0009_project_company_project_complete_per_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.company'),
        ),
    ]
