# Generated by Django 4.1.2 on 2022-11-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Estancado'), ('2', 'En proceso'), ('3', 'Finalizado')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Estancado'), ('2', 'En proceso'), ('3', 'Finalizado')], default=1, max_length=7),
        ),
    ]
